### PR TITLE
DFT and row/column for unknown characters log bug fixes

### LINKED ISSUE #12: DFT Bugs
The following cases are bugs:

### Case 1
When reading the file:
```
{ab}ab}
```
Current behaviour:
```
Classe: Comentário, Lexema: {ab}, Tipo: NULO
Classe: id, Lexema: ab, Tipo: NULO
Classe: , Lexema: }, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Classe: Comentário, Lexema: {ab}, Tipo: NULO
Erro na linha x coluna y, palavra ab} não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
### Case 2

File:
```
{{abab}}
```
Current behaviour:
```
Classe: Comentário, Lexema: {{abab}, Tipo: NULO
Classe: , Lexema: }, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Classe: Comentário, Lexema: {{abab}, Tipo: NULO
Erro na linha x coluna y, palavra } não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
````

### Case 3
File:
```
{{abab
```
Current behaviour:
```
Classe: , Lexema: {{abab, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Erro na linha x coluna y, palavra {{abab não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
````

### Case 4
File:
```
abab}}
```
Current behaviour:
```
Classe: id, Lexema: abab, Tipo: NULO
Classe: , Lexema: }}, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Erro na linha x coluna y, palavra abab}} não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
````

### PR DESCRIPTION
**Pull request by alefiury**
This PR tries to fix the DFT and row/column log related bugs.

### CODE REVIEW

File: src/lexer/scanner.go [hunk 1]
```diff
@@ -290,6 +305,11 @@ func (s *Scanner) Scan() Token {
 			s.dft.Reset()
 			s.file.Seek(-1, os.SEEK_CUR)
 
+			s.currentColumnFile -= n
```
Comment (MatheusNtg) [inline src/lexer/scanner.go:308]: Here, if we want to provide any information regarding to the word itself, maybe we should subtract the length of lexem, no?

Comment (alefiury) [reply src/lexer/scanner.go:308]: I agree, but I think that there are more things to be considered regarding the error information when we are dealing with words. This bug fix tries to specifically deal with unknown characters occurrence.

Comment (alefiury) [reply src/lexer/scanner.go:308]: We can deal with words in a future update.

**Review by MatheusNtg — APPROVED** [review]
